//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public System.Guid Order_ID { get; set; }
        public Nullable<System.Guid> Product_ID { get; set; }
        public Nullable<int> Production_amount { get; set; }
        public Nullable<System.Guid> Client_ID { get; set; }
        public Nullable<System.Guid> Departament_ID { get; set; }
        public Nullable<System.DateTime> Order_date { get; set; }
        public Nullable<System.DateTime> Date_of_completion { get; set; }
        public string Order_Status { get; set; }
        public string Comment { get; set; }
        public Nullable<System.Guid> OrderLifeCycleID { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Departments Departments { get; set; }
        public virtual Products Products { get; set; }
        public virtual OrderLifeCycle OrderLifeCycle { get; set; }
    }
}
